### ISSUE TITLE
Add unzip package

### ISSUE THREAD

**Issue by linquize** [docker-library/buildpack-deps#106]
It is quite common that packages are distributed in `.zip` instead of `tar.gz`.
I suggest to add `unzip` package to `buildpack-deps`.

ubuntu `unzip` package size is around 600KB which is small.

**Comment by tianon** [comment]
It's already included:

https://github.com/docker-library/buildpack-deps/blob/b26561e02c96fc42c9001edc1ecb1c4477fbab90/Dockerfile.template#L45

**Comment by linquize** [comment]
Oh! `buildpack-deps:focal-scm` does not have that but `buildpack-deps:focal` already has that.
