### ISSUE TITLE
Install git-lfs together with git

### ISSUE THREAD

**Issue by Brunni** [docker-library/buildpack-deps#112]
As of today, I expect git-lfs to be working wherever git is installed. Sadly it is missing in the scm-tags.

**Comment by tianon** [comment]
Hmm, I understand the sentiment, but my experience with LFS hasn't been exactly a positive one (and it's not a core feature of Git itself).

Looking at the numbers, this would add ~11MB to `buildpack-deps:buster-scm`, which is a roughly 3-4% size increase.

If we're talking about adding it to the primary non-scm variants (the "kitchen sink" images), I'd be much more inclined to agree it's a no-brainer.

**Comment by tianon** [comment]
Closing for now -- if there are users who need this, I'd recommend something like:

```dockerfile
FROM buildpack-deps:buster-scm
RUN apt-get update && apt-get install -y git-lfs && rm -rf /var/lib/apt/lists/*
```

(Or just downloading releases directly from the git-lfs project, which IIRC are distributed as easily-downloadable-binaries.)
