### ISSUE TITLE
Update git

### ISSUE THREAD

**Issue by vansergen** [docker-library/buildpack-deps#114]
It seems that only `buildpack-deps:sid` has the latest version of git - `2.28.0`.

- `buildpack-deps:jessie` - git version `2.1.4`
- `buildpack-deps:buster` - git version `2.20.1`
- `buildpack-deps:stretch` - git version `2.11.0`
-  `buildpack-deps:bullseye` - git version `2.27.0`

**Comment by wglambert** [comment]
That's how Debian does version control on their releases, those versions of `git` are at their most recent version for each distribution. Looking at the package [here](https://packages.debian.org/buster/git) you can see what version each distribution is on

See https://www.debian.org/releases/ 
https://wiki.debian.org/DebianStability
