### ISSUE TITLE
Add socat to builds

### ISSUE THREAD

**Issue by ianmacl** [docker-library/buildpack-deps#12]
The build images don't seem to have socat installed, which is incredibly handy for doing network routing between containers.  I propose that socat be added to the images.

**Comment by tianon** [comment]
From https://registry.hub.docker.com/_/buildpack-deps/:
> In spirit, buildpack-deps is similar to Heroku's stack images. It includes a large number of “development header” packages needed by various things like Ruby Gems, PyPI modules, etc. For example, buildpack-deps would let you do a bundle install in an arbitrary application directory without knowing beforehand that ssl.h is required to build a dependent module.

So, while `socat` is useful, it isn't a common requirement of language-specific package management systems.

**Comment by yosifkit** [comment]
Closing old issue, if you feel this was closed in error please let us know.
