### ISSUE TITLE
Request debian:bookworm

### ISSUE THREAD

**Issue by msg7086** [docker-library/buildpack-deps#123]
We maintain a OSS project and we use buildpack-dep as our base docker image to compile the project across multiple OS platforms. We are looking into compiling our project under Debian bookworm(currently testing) and we noticed that it's not available from buildpack-dep yet.

Do you have a plan to introduce bookworm in the near future?

Thanks!

**Comment by tianon** [comment]
We have supported Debian Testing previously, so I'm not opposed -- want to open a PR?
(If not, we'll get to it eventually.)
