### ISSUE TITLE
Unable to install  libgtk-3-dev with apt

### ISSUE THREAD

**Issue by WayneYe** [docker-library/buildpack-deps#131]
Hi experts,
I was unable to install `libgtk-3-dev` with apt:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgtk-3-dev : Depends: libatk-bridge2.0-dev but it is not going to be installed
                Depends: libatk1.0-dev (>= 2.15.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

By refering https://askubuntu.com/questions/899756/cant-install-npm-unable-to-correct-problems-you-have-held-broken-packages/978353#978353 I was able to install `aptitude` and successfully install it.

But i am wondering is there is way to install it with apt/apt-get instead of aptitude?

**Comment by tianon** [comment]
It would help to know which image tag you're using?  (It sounds like you're probably trying to use Debian Testing/Unstable or Ubuntu Devel :see_no_evil:)

**Comment by WayneYe** [comment]
@tianon I was using this image: [buildpack-deps:buster](https://hub.docker.com/_/buildpack-deps)

**Comment by WayneYe** [comment]
@tianon Indeed!  At the time i tried last week I wasn't able to install this lib, the command i ran was: `docker run -it buildpack-deps:buster bash`, just now i run it again seemed downloaded a newer version of it
And I am able to install it now....

Let 's close it for now, if i reproduce this again will try reopining it.

Thank you!
