### ISSUE TITLE
Getting signature error in docker image build for buildpack-deps:23.04-scm when doing sudo apt-get update

### ISSUE THREAD

**Issue by RamakrishnaHande** [docker-library/buildpack-deps#144]
I am using buildpack-deps:23.04-scm and all of a sudden, the build fails with below error. It was working last week. Should I do something to fix it ?

13:43:21 Get:2 http://security.ubuntu.com/ubuntu lunar-security InRelease [109 kB]
13:43:22 Err:2 http://security.ubuntu.com/ubuntu lunar-security InRelease
13:43:22   At least one invalid signature was encountered.
13:43:22 Get:3 http://archive.ubuntu.com/ubuntu lunar-updates InRelease [109 kB]
13:43:22 Err:1 http://archive.ubuntu.com/ubuntu lunar InRelease
13:43:22   At least one invalid signature was encountered.
13:43:22 Get:4 http://archive.ubuntu.com/ubuntu lunar-backports InRelease [99.8 kB]
13:43:22 Err:3 http://archive.ubuntu.com/ubuntu lunar-updates InRelease
13:43:22   At least one invalid signature was encountered.
13:43:23 Err:4 http://archive.ubuntu.com/ubuntu lunar-backports InRelease
13:43:23   At least one invalid signature was encountered.
13:43:23 Reading package lists...
13:43:23 [91mW: GPG error: http://security.ubuntu.com/ubuntu lunar-security InRelease: At least one invalid signature was encountered.
13:43:23 E: The repository 'http://security.ubuntu.com/ubuntu lunar-security InRelease' is not signed.
13:43:23 W: GPG error: http://archive.ubuntu.com/ubuntu lunar InRelease: At least one invalid signature was encountered.
13:43:23 E: The repository 'http://archive.ubuntu.com/ubuntu lunar InRelease' is not signed.
13:43:23 W: GPG error: http://archive.ubuntu.com/ubuntu lunar-updates InRelease: At least one invalid signature was encountered.
13:43:23 E: The repository 'http://archive.ubuntu.com/ubuntu lunar-updates InRelease' is not signed.
13:43:23 W: GPG error: http://archive.ubuntu.com/ubuntu lunar-backports InRelease: At least one invalid signature was encountered.
13:43:23 E: The repository 'http://archive.ubuntu.com/ubuntu lunar-backports InRelease' is not signed.
13:43:23 E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
13:43:23 E: Sub-process returned an error code

**Comment by tianon** [comment]
This is likely a seccomp denial failure -- I'd suggest updating libseccomp2, Docker, and runc on your host to resolve it.
