### ISSUE TITLE
Add zip package

### ISSUE THREAD

**Issue by loganmzz** [docker-library/buildpack-deps#145]
`unzip` command is available, but `zip` isn't

**Comment by tianon** [comment]
See "What's included?" in https://hub.docker.com/_/buildpack-deps (https://github.com/docker-library/docs/tree/master/buildpack-deps#whats-included). :eyes:

Can you describe which category you think `zip` would belong in, and maybe provide some example modules/packages in an ecosystem or two that rely on it? :sweat_smile: :bow:

**Comment by tianon** [comment]
Right, let me try to rephrase.  The goal of our set of packages is _installing_ modules, which does commonly require _un_-zipping, but _not_ commonly zipping (that's more of a packaging _creation_ concern, which is not the intent of this image). :sweat_smile:

**Comment by tianon** [comment]
Going to close for now, but happy to reconsider if we can find example modules which fail to install because they're missing `zip` :eyes:
