### ISSUE TITLE
Add gfortran

### ISSUE THREAD

**Issue by a86c6f7964** [docker-library/buildpack-deps#26]
What do y'all think about adding fortran into this. It looks like [python official](https://github.com/docker-library/python/blob/a467ae88510bf64dd4f35253d9a41af3b3cef7b6/2.7/Dockerfile) is using buildpack-deps:jessie and the philosophy of this project is to make it so that doing `pip install $PROJECT` works for most things. Right now `pip install scipy==0.15.1` does not work, but does work if I run
```
apt-get install --no-install-recommends -y gfortran gfortran-4.9 libgfortran-4.9-dev
```

**Comment by mattrobenolt** [comment]
I'd say gfortran is an extreme edge case imo. I'd be -1 on this, even though I work with projects that utilize scipy. :)

**Comment by yosifkit** [comment]
For reference:
```console
$ apt-get install gfortran gfortran-4.9 libgfortran-4.9-dev
...
After this operation, 21.8 MB of additional disk space will be used.
```

I agree with it being an edge case.

**Comment by tianon** [comment]
I also agree, but it does appear that the specific example given here works now:
```console
$ docker run -it --rm python:2 pip install scipy==0.15.1
Unable to find image 'python:2' locally
2: Pulling from library/python
357ea8c3d80b: Already exists 
52befadefd24: Already exists 
3c0732d5313c: Already exists 
ceb711c7e301: Already exists 
4211bb537697: Pull complete 
c48f01f3aad7: Pull complete 
72d54f32484a: Pull complete 
Digest: sha256:675765c16c09a0f1b5031cd8e568b1c33eebd65fd4c31b658033e3793e738d9f
Status: Downloaded newer image for python:2
Collecting scipy==0.15.1
  Downloading scipy-0.15.1-cp27-cp27mu-manylinux1_x86_64.whl (37.0MB)
    100% |████████████████████████████████| 37.0MB 24kB/s 
Installing collected packages: scipy
Successfully installed scipy-0.15.1
```
:+1:

**Comment by mattrobenolt** [comment]
All hail [PEP-0513](https://www.python.org/dev/peps/pep-0513/). 🙏
