### ISSUE TITLE
Add libdb-dev

### ISSUE THREAD

**Issue by jgehrcke** [docker-library/buildpack-deps#44]
I've used the `python:2.7` image which is based on `buildpack-deps:jessie`. The binaries for `libdb5.3` are contained in the image, but the headers are not. That leads to Python not building dbm support, yielding `ImportError: No module named dbm`.

Since the library is already contained in the image, let's allow to compile against it. I suggest adding the `libdb-dev` package. It only adds [a few kilobytes](https://packages.debian.org/jessie/libdb-dev).

**Comment by yosifkit** [comment]
Sounds reasonable to me.  cc @tianon

**Comment by tianon** [comment]
Agree! :+1:
