### ISSUE TITLE
clean jessie-scm container contains a coredump from auplink

### ISSUE THREAD

**Issue by sys-rq** [docker-library/buildpack-deps#47]
Problem description:
docker run --rm -it --name temp buildpack-deps:jessie-scm bash
ls -la /core
-rw------- 1 root root 8646656 Jun  9 21:37 core

file /core
core: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'auplink /mnt/scratch/var-lib-docker/aufs/mnt/fa1be5c3210b4a5444e6601bc92e1e7726'

**Comment by wglambert** [comment]
Doesn't seem to be an issue anymore

```console
$ docker run --rm -it --name temp buildpack-deps:jessie-scm bash
root@fbe9c536bb25:/# ls -la | grep core
root@fbe9c536bb25:/# 
```
