### ISSUE TITLE
Doubt about alpine tag

### ISSUE THREAD

**Issue by jaschweder** [docker-library/buildpack-deps#51]
Have you any plan to bring this image to Alpine for example ?

**Comment by tianon** [comment]
@jaschweder not especially -- IMO the goals of this base image and using Alpine as a base are fundamentally misaligned

Normally, one uses Alpine specifically to get smaller images.  This base image's main purpose is to include the entire kitchen sink irrespective of size. :sweat_smile:

**Comment by jaschweder** [comment]
@tianon I see, if there are any restriction, maybe I send some PR and see if everyone accept :)
