### ISSUE TITLE
Add http/2 support within curl images

### ISSUE THREAD

**Issue by MichaelSimons** [docker-library/buildpack-deps#57]
## Steps to reproduce
1. docker run -it --rm buildpack-deps:curl
2. curl --http2 -I https://nghttp2.org/

## Expected Results
curl is configured to make http/2 requests

## Actual Results
Unsupported protocol error

**Comment by tianon** [comment]
`buildpack-deps:curl` is based on the stable release of Debian, which is currently Debian Jessie -- if you switch to `buildpack-deps:stretch-curl`, you'll get an image based on Debian Testing (the in-progress next release of Debian), which is more likely to include a version of `curl` which properly supports HTTP/2

**Comment by michael-k** [comment]
Stretch was released in the meantime and *buildpack-deps:curl* has support for HTTP/2.  Therefore I assume that the issue can be closed.

**Comment by tianon** [comment]
Nice catch, thanks!
