### ISSUE TITLE
Wheezy EOL LTS?

### ISSUE THREAD

**Issue by king-jam** [docker-library/buildpack-deps#73]
Given this information: https://en.wikipedia.org/wiki/Debian_version_history#Release_table

Will you be dropping Wheezy from support in May?

**Comment by yosifkit** [comment]
I believe that is the plan, yes.

**Comment by king-jam** [comment]
Thanks! Leave this open for tracking or close it?

**Comment by tianon** [comment]
Let's close until there's something actionable. :+1:
