### ISSUE TITLE
use debian slim baseimages

### ISSUE THREAD

**Issue by chpio** [docker-library/buildpack-deps#78]
Hallo,

using debian slim baseimages should bring the size down by a few MBs, without really compromising features. The con is the missing documentation.

**Comment by tianon** [comment]
To be frank, the primary use case of `buildpack-deps` is for folks who don't care as much about size and instead simply want the entire kitchen sink included by default, so unless the size difference is a _really_ dramatic percentage, this change isn't going to be very compelling.

**Comment by FrnchFrgg** [comment]
Using slim bases would probably be relevant for the curl and scm variants since they are a lot smaller. For the regular variant, not so much, but it is convenient to base it on the scm variant so it would inherit the "slim"ness...
