### ISSUE TITLE
Add nasm and yasm assemblers?

### ISSUE THREAD

**Issue by sgsunder** [docker-library/buildpack-deps#82]
I frequently run into projects that require nasm and/or yasm assemblers to build, so this could be a useful addition, plus it only weighs about 20MB on the Debian image.

**Comment by tianon** [comment]
Do you have a couple open source example projects you could share
(especially for posterity's sake)?

**Comment by sgsunder** [comment]
The largest open-source project i've ran into that requires it would be ffmpeg and its defendant library, libx264, both of which require them to compile.

- https://git.ffmpeg.org/gitweb/ffmpeg.git
- https://git.videolan.org/?p=x264.git

**Comment by tianon** [comment]
Interesting -- I hadn't really considered this being a base for building software generically; here's the description of what `buildpack-deps` contains that we use on https://hub.docker.com/_/buildpack-deps/:

> It includes a large number of "development header" packages needed by various things like Ruby Gems, PyPI modules, etc. For example, `buildpack-deps` would let you do a `bundle install` in an arbitrary application directory without knowing beforehand that `ssl.h` is required to build a dependent module.

(See also the "What's included?" section further below, which goes into more detail.)

Are there any popular language modules (Gems, etc) which require `nasm` or `yasm` for building?

**Comment by tianon** [comment]
Closing for now, but to be clear, if we can find a ~decent number of example language modules using `nasm` or `yasm` I'm open to rediscussing:

> Are there any popular language modules (Gems, etc) which require `nasm` or `yasm` for building?
