### ISSUE TITLE
npm not included but docs say it is...?

### ISSUE THREAD

**Issue by deathgaze** [docker-library/buildpack-deps#83]
Readme at main site on docker hub states that npm is included in this image with other build tools, but when I run simple Dockerfile with it, I get npm not found error.
```
FROM buildpack-deps
RUN git clone https://github.com/screeps/screeps.git
WORKDIR ./screeps
EXPOSE 21025 21026
RUN npm install screeps # error here!
RUN npx screeps init
CMD ["npx", "screeps", "start"]
```

**Comment by wglambert** [comment]
This is a somewhat semantical issue, the docs don't explicitly state that gem, npm, or python is installed with it, just that they should work without the need for header/dev packages
>npm install / pip install should be successful without additional header/development packages.

Looking at an example `Dockerfile` for npm usage:
https://github.com/docker-library/node/blob/master/0.11/Dockerfile

Using buildpack-deps as the base: node is installed which contains npm
