### ISSUE TITLE
Add aria2c

### ISSUE THREAD

**Issue by KOLANICH** [docker-library/buildpack-deps#89]
I suggest to add aria2c to the image and use it in the dependent images instead of `curl` and `wget`. aria2c is a multistream downloader which downloads files faster and deals better with connections instabilities.

**Comment by tianon** [comment]
Under the frame of the image description, where does `aria2c` fit in?

> The main tags of this image are the full batteries-included approach. With them, a majority of arbitrary `gem install` / `npm install` / `pip install` should be successful without additional header/development packages.

Are there gems or packages which use/need `aria2c`?

We already include _both_ of `curl` and `wget`, so it seems like overkill to add yet another file-downloading-tool by default.

**Comment by tianon** [comment]
That explains what it _is_, but doesn't really answer my question about whether it's used directly by any gems/modules/etc.

Given the popularity of `curl` and `wget` (compared to this tool which I'm hearing about for the first time in this thread -- nothing against it, but I can't really see the popularity of it matching that of `curl` or `wget` which are used in countless scripts/projects across the entire software ecosystem), I'm inclined to not add this now unless/until we can find a popular module which requires it (otherwise we're opening the door for other alternative download managers as well, and this image is already bloated enough as it is).

Thanks!

**Comment by KOLANICH** [comment]
>but I can't really see the popularity of it matching that of curl or wget which are used in countless scripts/projects across the entire software ecosystem

The popularity doesn't match, curl and wget are usually used because aria has a bad CLI - the default settings are useless (not activating multistream download and memory mapped files, for example) and harmful (like file preallocation, should be disabled), I don't remember the spelling of the needed flags and have to look at help (or into my previous shell scripts using aria2c) every time I use it. curl and wget have less friction to use.

>I'm inclined to not add this now unless/until we can find a popular module which requires it

What do you mean? Do you need proofs of aria2c popularity? Here they are: [1](https://github.com/rg3/youtube-dl/blob/master/README.md#readme) [2](https://github.com/coursera-dl/coursera-dl/blob/a82edb924/coursera/commandline.py#L257) [3](https://github.com/pyenv/pyenv/issues/534)  [4](https://github.com/tsgates/arch-wiki-markdown/blob/master/wiki/Improve_Pacman_Performance.md) [5](https://github.com/Winetricks/winetricks/commit/4ea5d13370e3c43cae989798d7b96c40f02ecece) [6](https://github.com/tatsuhiro-t/apt-metalink) [7](https://github.com/robbielj/chrome-aria2-integration) [8](https://github.com/Metalnem/send-to-aria2)

**Comment by tianon** [comment]
> aria has a bad CLI - the default settings are useless (not activating multistream download and memory mapped files, for example) and harmful (like file preallocation, should be disabled), I don't remember the spelling of the needed flags and have to look at help (or into my previous shell scripts using aria2c) every time I use it. curl and wget have less friction to use.

Honestly this reads to me like a pretty strong recommendation _against_ aria2c, which I imagine probably wasn't your intent?

**Comment by KOLANICH** [comment]
>Honestly this reads to me like a pretty strong recommendation against aria2c, which I imagine probably wasn't your intent?

It is a drawback. But it cannot be a recommendation against aria2c - there is no alternative. Other free open source download managers are either GUI (most of which are only GUI forwarding the stuff to aria2c process), or don't support multi-stream downloads. The best what can be done here is to improve aria.
