### ISSUE TITLE
Use images with backported packages as base images for Debian

### ISSUE THREAD

**Issue by KOLANICH** [docker-library/buildpack-deps#91]

**Comment by tianon** [comment]
When you open issues like this, please do us a favor and provide detail about your use case (what are you trying to accomplish? why can't you accomplish it with the existing image? what do you expect us to do about it and how do you expect that to change the way you expect to use it?).  As it stands right now, there's no rationale here for _why_ we should consider doing anything here, so I'm inclined to close the issue instead.

**Comment by KOLANICH** [comment]
Because packages in stable are always of some old obsolete version. No specific rationale why, `later` doesn't necessarily mean `better`.

**Comment by tianon** [comment]
Given that Debian's Backports repository is not officially supported by either the Debian Security Team or the Debian Release Team (and relies instead on the diligence of the individual Debian Developers who maintain each backported package to perform timely updates), I'm going to close this as something we do not intend to do.
