### ISSUE TITLE
Add libmaxminddb-dev

### ISSUE THREAD

**Issue by mattrobenolt** [docker-library/buildpack-deps#95]
buildpack-deps already includes `libgeoip-dev`, and this library is deprecated from Maxmind. The replacement is `libmaxminddb-dev`. It's not even possible (ok, it's possible, but it's very hard) to get the database files that are read by `libgeoip` since Maxmind doesn't distribute them anymore.

Any opposition to bringing in the newer version?

https://github.com/maxmind/geoip-api-c/blob/master/README.md
vs
https://github.com/maxmind/libmaxminddb/blob/master/README.md

An argument can even be made to remove `libgeoip-dev` since this isn't really a supported library anymore, but I image ripping things out would cause more heartache. 💔

**Comment by yosifkit** [comment]
It has been been about 4 years since we added `libgeoip-dev` (https://github.com/docker-library/buildpack-deps/pull/34). Perhaps we swap to `libmaxmind` for `buster` and above.

What do you think @tianon?

**Comment by tianon** [comment]
Agreed, sounds sane!

**Comment by mattrobenolt** [comment]
lol I forgot that I added it originally.

**Comment by tianon** [comment]
I think the only place `libmaxminddb-dev` is not available out of what we support is Jessie.

Given that `libgeoip-dev` is really not supported anymore (and there's no useful public source of data for it), I'm in favor of just swapping outright as a signal to downstream folks that they really should be aware of breakage here and should perhaps look to ditch their use of GeoIP.
