### ISSUE TITLE
Is it possible we can update git version int this Image

### ISSUE THREAD

**Issue by gengjiawen** [docker-library/buildpack-deps#96]
Related issue: https://github.com/nodejs/docker-node/issues/1062.

**Comment by tianon** [comment]
We only provide stock packages from the relevant distributions -- thus, if you want newer Git, you need to use a newer distribution.

**Comment by Surya-smart619** [comment]
Hi @tianon, I'm new to using docker, what is the newer distribution with git version >=2.13.0, and how to I use it to resolve this issue?

**Comment by tianon** [comment]
Sounds like you just need to update from Debian Stretch (Git 2.11) to
Buster (Git 2.20).
