### ISSUE TITLE
Add a Debian Slim variant

### ISSUE THREAD

**Issue by jaztec** [docker-library/buildpack-deps#99]
Firstly, I saw issue #78 and the reason to close it, however, the success of this library has preceded itself and other contributers are using it as a base template for their images. Like https://github.com/docker-library/golang.

At this point Golang is using the SCM variant of this set for their Debian builds and Alpine for their slim builds but it would be really nice to have a Debian slim build to be able to utilize the pro's of Debian with the reduced size of Alpine in, at least, that specific branch of the SCM tree.

Please reconsider adding a slim branch in this repository for a buster-(slim-)curl and a buster-(slim-)scm image. 

I volunteer contribution by the way if it is required.

**Comment by tianon** [comment]
This repository currently has ~30 *unique* variations already -- IMO the value of having something that's "batteries included, but somewhat slimmer" is a bit too low for us to want to maintain such a thing (we already support far too much here :disappointed:).
